# Generated by Django 5.0.1 on 2025-01-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('progress', models.CharField(choices=[('not-started', '未开始'), ('in-progress', '进行中'), ('completed', '完成')], default='not-started', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
