# Generated by Django 5.0.1 on 2025-02-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victory',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('state', models.BooleanField()),
            ],
        ),
    ]
